name: "Check if \"Run tests\" action succeeded"

on:
    pull_request:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    pr-run-test-action:
        name: Check if \"Run tests\" action succeeded
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: node install
              run: cd ./.github/helpers && npm i
            - name: Calling github API
              run: cd ./.github/helpers && REPO=${{ github.repository }} JOB_ID=${{ github.job }} node test-pass-check-pr.js